language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
script:
- yarn test
deploy:
  provider: npm
  email: darioajr@gmail.com
  api_key:
    secure: Yvr2tqh97U5aEhXaWQJcl+3vCbLq7RxnwcF7qapHV/NxLMP59fniP0R4SJaGWrUSK1zAreJiyY4Kv2ukjF2FuakEFUBm1bTLe3KV2gZIz9BPYBqHfJFS7moJaUmV/Crn2fnJYSUPCgkkfJQmhrvGFzk4cBh8YGbIhPKwN1LVJz/BWjz6VCZArA+dDZY5zUqfRRqKTy+q/5LeBSrmydxa8sDY+pdfUwI6rSyb7j2wvLpM2ou5e1+hWB7vRKpemsJUQtg2AZjkhoo1nBZIDoHvowwUia7cAdnP11qim7IRlBUDnQJe8WwBkubT/rKSE0OodmHeNHKvF5X46hPaBxmDFTiGWAHLmDflGGnQ9stGWdOgV1a8Gj7a323VPziU1qyJh0V3dmbkW2TJU0/4MCEc9fbEU0DRWctxOtPohtBxpvkHcZ6YOI7omgxEsJsWFInMMWqUVM2gotlTFYHa/EyoTzQz1UA2wCzWwVmFkXf5rJZGWDwsASueuYMvlvmAiyGnYuCg53vh7lfraTcMJx1T7TNLMWnwfw9iS1cBE7KLIzGVr3DqJxdxchGW6zUkLyud0eqhvguQh/JRe/i/3McT4TuQhukCkj/OPhr0p6iOIBeV+te9VcUH+esZvS1NWt9emJW4KF9A8zGZ+r5qem/xMH/C9UX+IY3ympNwqD6FxoA=
  on:
    tags: true
    repo: darioajr/react-native-image-listitem
    condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+.*$"
